### ISSUE TITLE
The RTL is not working! 

### ISSUE THREAD

**Issue by manssorr** [obahareth/notion-rtl#24] opened 2021-09-25 10:36 UTC
Today I found that the RTL not working on the Website or Notion Enhancer, Is this only with me>

**Comment by dragonwocky** [comment] 2021-09-25 13:57
A temporary solution is described here for the notion-enhancer until this officially updates: https://github.com/notion-enhancer/notion-enhancer/issues/589

(The same could be achieved on the web by using something like Greasemonkey to run the JS.)

**Comment by obahareth** [comment] 2021-09-26 12:56
@manssorr What browser are you using? I gave it a try today on Chrome and there seem to be issues with database pages it only works if you open a nested page, I opened #25 for this.

Pages seem to work without issues for me though.

Can you try the [public testing pages](https://www.notion.so/obahareth/Notion-RTL-Tests-8bee4db6585343fc8bae93b791edd726) and let me know if you're still having issues?

**Comment by Fahme** [comment] 2021-09-26 13:36
I tested the extension on Firefox too everything seems to work fine.

Double check you're using the store version and if you're still experiencing the issues, can we have a more detailed bug report ?

**Comment by Fahme** [comment] 2021-09-28 17:22
> I'm using chrome, and never works with me now on subpages or on database pages :(

Can you do the following :  

- Create new profile on chrome 
- make sure there's no extensions are installed on it 
- install notion-rtl extension
- go to https://www.notion.so/obahareth/Notion-RTL-Tests-8bee4db6585343fc8bae93b791edd726

is the content aligned ??

**Comment by obahareth** [comment] 2021-09-29 09:13
@Fahme I'm getting a lot of people mentioning this issue on DMs too, I think it's actually just issue #25.
Can you check [this comment](https://github.com/notion-enhancer/notion-enhancer/issues/589#issuecomment-927319542) from dragonwocky?

**Comment by Fahme** [comment] 2021-09-29 09:16
> @Fahme I'm getting a lot of people mentioning this issue on DMs too, I think it's actually just issue #25. Can you check [this comment](https://github.com/notion-enhancer/notion-enhancer/issues/589#issuecomment-927319542) from dragonwocky?

Yes, i know the root cause i've already fixed it, running some tests and i'll push a PR for a review today or tomorrow latest.

**Comment by SajadJalilian** [comment] 2021-09-29 14:22
I have the same problem after recent chrome update

**Comment by Fahme** [comment] 2021-09-29 20:05
> I have the same problem after recent chrome update

we're working on a fix feel free to check #27 to know when the fix will be merged

**Comment by Fahme** [comment] 2021-09-29 20:26
@manssorr we appreciate your help in testing this PR too #27

**Comment by manssorr** [comment] 2021-09-29 20:35
@Fahme 
I'm glad that was helpful, I really didn't do anything. You guys are doing a great effort. Thank you for making our Arabic language experience easier and more efficient. I really appreciate that.

**Comment by Fahme** [comment] 2021-09-30 07:54
> @Fahme I'm glad that was helpful, I really didn't do anything. You guys are doing a great effort. Thank you for making our Arabic writing experience easier and more efficient. I really appreciate that.

Thanks for your words, can you help us test the PR updates too ?

**Closed** 2021-09-30 14:28 UTC
Labels: bug

**Comment by manssorr** [comment] 2021-09-30 15:00
It works like a charm!!
